### ISSUE TITLE
Wrong Links in the "Student Projects"-List

### ISSUE THREAD

**Issue by BenjaminBrodwolf** [Dierk/Home#1]
In the [index.html-File](https://github.com/Dierk/Home/blob/master/docs/index.html) the Projects  **[Lambda Kalkül für praktisches JavaScript](https://github.com/Dierk/Home/blob/9fedb56d609953d6c738c54ec3089357f352a0ad/docs/index.html#L102)** and **[Facettierte Suche in Web UIs mit Geo-Informationen](https://github.com/Dierk/Home/blob/9fedb56d609953d6c738c54ec3089357f352a0ad/docs/index.html#L105)** are linked incorrectly. It should be the other way around. ;-)

**Comment by Dierk** [comment]
thanks! if ok now, please close the issue
